---
- name: ec2 launcher
  hosts: localhost
  connection: local
  tasks:
          - name: launching ec2
            ec2:
                    instance_type: t2.micro
                    key_name: Mumbai-rajat
                    image: ami-0108d6a82a783b352
                    region: ap-south-1
                    group: default
                    count: 2
                    vpc_subnet_id: subnet-07d741c9adc0458e3
                    wait: yes
                    assign_public_ip: yes


